import express from "express";
import multer from "multer";
import knexLib from "knex";
import knexConfig from "../knexfile.js";
import { v4 as uuidv4 } from "uuid";
import logChange from "../middleware/changeLog.js";
import path from "path";
import { fileURLToPath } from "url";

// Get the current directory name
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const knex = knexLib(knexConfig);
const router = express.Router();

// Configure multer for file uploads to the 'gallery' folder
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, "gallery/"); // Save files in the 'gallery' folder
  },
  filename: (req, file, cb) => {
    const uniqueSuffix = Date.now() + '-' + uuidv4(); // Generate a unique suffix
    const uniqueName = uniqueSuffix + "-" + file.originalname; // Unique filename
    cb(null, uniqueName); // Use the unique filename
  },
});
const upload = multer({ storage });

// Create a new image
router.post("/:type", upload.single("image"), async (req, res) => {
  const authHeader = req.headers.authorization;
  const token = authHeader && authHeader.split(" ")[1];
  const { type } = req.params;
  const { category, subcategory, description } = req.body;
  // console.log(req.body);

  if (!req.file) {
    return res.status(400).json({ error: "Image file is required" });
  }

  try {
    const uniqueName = req.file.filename; // Use the filename generated by multer

    // Save the image details to the database
    const [id] = await knex("images").insert({
      name: uniqueName, // Save the unique filename in the database
      category: category, // Save category name
      subcategory: subcategory, // Save subcategory name
      description: description, // Save image description
      type: type, // Save image type
    });

    await logChange(token, "Image", "INSERT", id, { name: uniqueName, category, subcategory, description });

    res.status(201).json({ id, name: uniqueName }); // Return the unique filename
  } catch (error) {
    console.error("Error creating image:", error.message);
    res.status(500).json({ error: "Error creating image", details: error.message });
  }
});

// Post a new image by category name
router.post("/category/:category/:type", upload.single("image"), async (req, res) => {
  const { category, type } = req.params;

  if (!req.file) {
    return res.status(400).json({ error: "Image file is required" });
  }

  try {
    const { description } = req.body; // Get additional fields
    const uniqueName = req.file.filename; // Use the filename generated by multer

    // Save the image details to the database
    const [id] = await knex("images").insert({
      name: uniqueName, // Save the unique filename in the database
      category, // Save category name
      description, // Save image description
      type, // Save image type
    });

    res.status(201).json({ id, name: uniqueName }); // Return the unique filename
  } catch (error) {
    console.error("Error creating image by category:", error.message);
    res.status(500).json({ error: "Error creating image by category", details: error.message });
  }
});

// Get all images
router.get("/:type", async (req, res) => {
  try {
    const images = await knex("images").where({ type: req.params.type }).select("*");
    res.status(200).json(images);
  } catch (error) {
    res.status(500).json({ error: "Error fetching images", details: error.message });
  }
});

// Get an image by ID
router.get("/:id", async (req, res) => {
  try {
    const image = await knex("images").where({ id: req.params.id }).first();
    if (!image) {
      return res.status(404).json({ error: "Image not found" });
    }
    res.status(200).json(image);
  } catch (error) {
    res.status(500).json({ error: "Error fetching image", details: error.message });
  }
});
// get all images by category name
router.get("/category/:category", async (req, res) => {
  const { category } = req.params;
  const images = await knex("images").where({ category }).select("*");
  if (!images) {
    return res.status(404).json({ error: "Images not found" });
  }
  res.status(200).json(images);
});

// Update an image by ID
router.put("/:id", upload.single("image"), async (req, res) => {
  const authHeader = req.headers.authorization;
  const token = authHeader && authHeader.split(" ")[1];

  const newData = req.body;
  if (req.file) {
    newData.name = req.file.filename; // Use the filename generated by multer
  }

  try {
    const { id } = req.params;
    const currentData = await knex("images").where({ id }).first();
    if (!currentData) {
      return res.status(404).json({ error: "Image not found" });
    }

    const changes = {};
    for (const key in newData) {
      if (currentData[key] !== newData[key]) {
        changes[key] = {
          old: currentData[key],
          new: newData[key],
        };
      }
    }

    if (Object.keys(changes).length > 0) {
      await logChange(token, "Image", "UPDATE", id, changes);
    }

    await knex("images").where({ id }).update(newData);
    res.status(200).json({ message: "Image updated successfully", changes });
  } catch (error) {
    console.error("Error updating image:", error.message);
    res.status(500).json({ error: "Error updating image", details: error.message });
  }
});

// Delete an image by ID
router.delete("/:id", async (req, res) => {
  const authHeader = req.headers.authorization;
  const token = authHeader && authHeader.split(" ")[1];

  if (!token) {
    return res.status(401).json({ error: "Unauthorized: Token is missing" });
  }

  try {
    const { id } = req.params;
    const imageDetails = await knex("images").where({ id }).first();

    if (!imageDetails) {
      return res.status(404).json({ error: "Image not found" });
    }

    const deletedCount = await knex("images").where({ id }).del();

    if (deletedCount === 0) {
      return res.status(404).json({ error: "Image could not be deleted." });
    }

    const changes = {
      deleted_image: imageDetails,
    };
    await logChange(token, "images", "DELETE", id, changes);

    res.status(200).json({ message: "Image deleted successfully." });
  } catch (error) {
    console.error("Error deleting image:", error);
    res.status(500).json({ error: "Error deleting image.", details: error.message });
  }
});

// Serve an image by filename
router.get("/image/:filename", (req, res) => {
  const { filename } = req.params;
  const filePath = path.join(__dirname, "../gallery", filename); // Adjust the path as necessary

  res.sendFile(filePath, (err) => {
    if (err) {
      console.error("Error serving image:", err);
      res.status(err.status).end();
    }
  });
});

export default router;
